# Generated by Django 4.0.2 on 2022-04-12 06:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0004_alter_customuser_currency'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='customuser',
            name='currency',
        ),
        migrations.AddField(
            model_name='customuser',
            name='money',
            field=models.FloatField(default=0, null=True),
        ),
        migrations.DeleteModel(
            name='Currency',
        ),
    ]
