# Generated by Django 4.0.2 on 2022-04-12 10:36

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeapp', '0001_initial'),
        ('users', '0005_remove_customuser_currency_customuser_money_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='customuser',
            name='stock',
            field=models.ForeignKey(default='', null=True, on_delete=django.db.models.deletion.CASCADE, to='exchangeapp.stock'),
        ),
    ]
