# Generated by Django 4.0.2 on 2022-04-12 22:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('users', '0007_remove_customuser_stock'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='money',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, null=True),
        ),
    ]
