# Generated by Django 4.0.2 on 2022-04-12 21:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeapp', '0003_portfolio'),
    ]

    operations = [
        migrations.AddField(
            model_name='stock',
            name='price',
            field=models.FloatField(default=1, null=True),
        ),
        migrations.AlterField(
            model_name='portfolio',
            name='quantity',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='количество'),
        ),
    ]
