# Generated by Django 4.0.2 on 2022-04-13 08:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeapp', '0004_stock_price_alter_portfolio_quantity'),
    ]

    operations = [
        migrations.AddField(
            model_name='portfolio',
            name='total_price',
            field=models.PositiveIntegerField(default=0, null=True, verbose_name='стоимость'),
        ),
    ]
