# Generated by Django 4.0.2 on 2022-04-13 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('exchangeapp', '0006_alter_stock_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='portfolio',
            name='total_price',
            field=models.DecimalField(decimal_places=3, default=0, max_digits=10, null=True, verbose_name='стоимость'),
        ),
    ]
